global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana-agent'
    static_configs:
      - targets: ['grafana-agent:12345']  # Grafana Agent metrics endpoint

