server:
  log_level: info

metrics:
  wal_directory: /tmp/agent_wal
  global:
    scrape_interval: 15s
  configs:
    - name: default
      scrape_configs:
        - job_name: node_exporter
          static_configs:
            - targets: ["node-exporter:9100"]

logs:
  configs:
    - name: default
      clients:
        - url: http://loki:3100/loki/api/v1/push
      positions:
        filename: /tmp/positions.yaml
      target_config:
        sync_period: 10s
      scrape_configs:
        - job_name: varlogs
          static_configs:
            - targets:
                - localhost
              labels:
                job: varlogs
                host: agent
                __path__: /var/log/*.log

